"""admin session

Revision ID: 0fe6ce118a73
Revises: 930371cd3879
Create Date: 2024-09-14 15:38:35.040428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fe6ce118a73'
down_revision = '930371cd3879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_admin_session', schema=None) as batch_op:
        batch_op.drop_constraint('active_admin_session_admin_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['admin_id'], ['id'])
        batch_op.drop_column('last_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_admin_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('active_admin_session_admin_id_key', ['admin_id'])

    # ### end Alembic commands ###
