"""ganti sql

Revision ID: ace4063b4b5a
Revises: 
Create Date: 2024-07-10 20:37:49.809991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace4063b4b5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_siswa', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('kelas', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siswa_id_siswa'), ['id_siswa'], unique=False)
        batch_op.create_index(batch_op.f('ix_siswa_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siswa_name'))
        batch_op.drop_index(batch_op.f('ix_siswa_id_siswa'))

    op.drop_table('siswa')
    # ### end Alembic commands ###
