"""ubah pose dan ekspresi

Revision ID: c024c6ee16ec
Revises: 0fe6ce118a73
Create Date: 2024-09-15 00:16:21.180100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c024c6ee16ec'
down_revision = '0fe6ce118a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expresion_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('expresion', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expresion_data')
    # ### end Alembic commands ###
